<?php

return [
    // Temporary preview: the login screen opens the public home page.
    'demo_login' => env('DEMO_LOGIN_ENABLED', false),
    'universities' => [
        'umm_al_qura' => ['ar' => 'جامعة أم القرى', 'en' => 'Umm Al-Qura University'],
        'islamic_university' => ['ar' => 'الجامعة الإسلامية بالمدينة المنورة', 'en' => 'Islamic University of Madinah'],
        'imamu' => ['ar' => 'جامعة الإمام محمد بن سعود الإسلامية', 'en' => 'Imam Mohammad Ibn Saud Islamic University'],
        'ksu' => ['ar' => 'جامعة الملك سعود', 'en' => 'King Saud University'],
        'kau' => ['ar' => 'جامعة الملك عبدالعزيز', 'en' => 'King Abdulaziz University'],
        'kfupm' => ['ar' => 'جامعة الملك فهد للبترول والمعادن', 'en' => 'King Fahd University of Petroleum and Minerals'],
        'kfu' => ['ar' => 'جامعة الملك فيصل', 'en' => 'King Faisal University'],
        'kku' => ['ar' => 'جامعة الملك خالد', 'en' => 'King Khalid University'],
        'qu' => ['ar' => 'جامعة القصيم', 'en' => 'Qassim University'],
        'taibahu' => ['ar' => 'جامعة طيبة', 'en' => 'Taibah University'],
        'tu' => ['ar' => 'جامعة الطائف', 'en' => 'Taif University'],
        'uoh' => ['ar' => 'جامعة حائل', 'en' => 'University of Hail'],
        'jazanu' => ['ar' => 'جامعة جازان', 'en' => 'Jazan University'],
        'ju' => ['ar' => 'جامعة الجوف', 'en' => 'Al Jouf University'],
        'bu' => ['ar' => 'جامعة الباحة', 'en' => 'Al Baha University'],
        'ut' => ['ar' => 'جامعة تبوك', 'en' => 'University of Tabuk'],
        'nu' => ['ar' => 'جامعة نجران', 'en' => 'Najran University'],
        'nbu' => ['ar' => 'جامعة الحدود الشمالية', 'en' => 'Northern Border University'],
        'pnu' => ['ar' => 'جامعة الأميرة نورة بنت عبدالرحمن', 'en' => 'Princess Nourah bint Abdulrahman University'],
        'ksau_hs' => ['ar' => 'جامعة الملك سعود بن عبدالعزيز للعلوم الصحية', 'en' => 'King Saud bin Abdulaziz University for Health Sciences'],
        'iau' => ['ar' => 'جامعة الإمام عبدالرحمن بن فيصل', 'en' => 'Imam Abdulrahman Bin Faisal University'],
        'psau' => ['ar' => 'جامعة الأمير سطام بن عبدالعزيز', 'en' => 'Prince Sattam bin Abdulaziz University'],
        'su' => ['ar' => 'جامعة شقراء', 'en' => 'Shaqra University'],
        'mu' => ['ar' => 'جامعة المجمعة', 'en' => 'Majmaah University'],
        'seu' => ['ar' => 'الجامعة السعودية الإلكترونية', 'en' => 'Saudi Electronic University'],
        'uj' => ['ar' => 'جامعة جدة', 'en' => 'University of Jeddah'],
        'ub' => ['ar' => 'جامعة بيشة', 'en' => 'University of Bisha'],
        'kaust' => ['ar' => 'جامعة الملك عبدالله للعلوم والتقنية', 'en' => 'King Abdullah University of Science and Technology'],
        'uhb' => ['ar' => 'جامعة حفر الباطن', 'en' => 'University of Hafr Al Batin'],
        'alfaisal' => ['ar' => 'جامعة الفيصل', 'en' => 'Alfaisal University'],
        'psu' => ['ar' => 'جامعة الأمير سلطان', 'en' => 'Prince Sultan University'],
        'dar_alhekma' => ['ar' => 'جامعة دار الحكمة', 'en' => 'Dar Al-Hekma University'],
        'effat' => ['ar' => 'جامعة عفت', 'en' => 'Effat University'],
        'ubt' => ['ar' => 'جامعة الأعمال والتكنولوجيا', 'en' => 'University of Business and Technology'],
        'yamamah' => ['ar' => 'جامعة اليمامة', 'en' => 'Al Yamamah University'],
        'sulaiman_alrajhi' => ['ar' => 'جامعة سليمان الراجحي', 'en' => 'Sulaiman Al Rajhi University'],
        'daru_uloom' => ['ar' => 'جامعة دار العلوم', 'en' => 'Dar Al Uloom University'],
        'riyadh_elm' => ['ar' => 'جامعة رياض العلم', 'en' => 'Riyadh Elm University'],
        'maarefa' => ['ar' => 'جامعة المعرفة', 'en' => 'AlMaarefa University'],
        'future' => ['ar' => 'جامعة المستقبل', 'en' => 'University of the Future'],
        'arab_open' => ['ar' => 'الجامعة العربية المفتوحة - فرع السعودية', 'en' => 'Arab Open University - Saudi Arabia Branch'],
    ],
    'degrees' => [
        'diploma' => ['ar' => 'دبلوم', 'en' => 'Diploma'],
        'associate' => ['ar' => 'درجة مشارك', 'en' => 'Associate degree'],
        'bachelor' => ['ar' => 'بكالوريوس', 'en' => 'Bachelor’s degree'],
        'postgraduate_diploma' => ['ar' => 'دبلوم عالي', 'en' => 'Postgraduate diploma'],
        'master' => ['ar' => 'ماجستير', 'en' => 'Master’s degree'],
        'doctorate' => ['ar' => 'دكتوراه', 'en' => 'Doctoral degree'],
    ],
    'majors' => [
        'business_administration' => ['ar' => 'إدارة الأعمال', 'en' => 'Business Administration'],
        'accounting' => ['ar' => 'المحاسبة', 'en' => 'Accounting'],
        'finance' => ['ar' => 'المالية', 'en' => 'Finance'],
        'marketing' => ['ar' => 'التسويق', 'en' => 'Marketing'],
        'human_resources' => ['ar' => 'الموارد البشرية', 'en' => 'Human Resources'],
        'management_information_systems' => ['ar' => 'نظم المعلومات الإدارية', 'en' => 'Management Information Systems'],
        'supply_chain' => ['ar' => 'إدارة سلسلة الإمداد', 'en' => 'Supply Chain Management'],
        'economics' => ['ar' => 'الاقتصاد', 'en' => 'Economics'],
        'entrepreneurship' => ['ar' => 'ريادة الأعمال', 'en' => 'Entrepreneurship'],
        'public_administration' => ['ar' => 'الإدارة العامة', 'en' => 'Public Administration'],
        'project_management' => ['ar' => 'إدارة المشاريع', 'en' => 'Project Management'],
        'operations_management' => ['ar' => 'إدارة العمليات', 'en' => 'Operations Management'],
        'business_analytics' => ['ar' => 'تحليلات الأعمال', 'en' => 'Business Analytics'],
        'international_business' => ['ar' => 'الأعمال الدولية', 'en' => 'International Business'],
        'banking' => ['ar' => 'الأعمال المصرفية', 'en' => 'Banking'],
        'risk_management' => ['ar' => 'إدارة المخاطر', 'en' => 'Risk Management'],
        'ecommerce' => ['ar' => 'التجارة الإلكترونية', 'en' => 'E-commerce'],
        'business_law' => ['ar' => 'القانون التجاري', 'en' => 'Business Law'],
        'actuarial_science' => ['ar' => 'العلوم الاكتوارية', 'en' => 'Actuarial Science'],
        'accounting_information_systems' => ['ar' => 'نظم المعلومات المحاسبية', 'en' => 'Accounting Information Systems'],
        'computer_science' => ['ar' => 'علوم الحاسب', 'en' => 'Computer Science'],
        'software_engineering' => ['ar' => 'هندسة البرمجيات', 'en' => 'Software Engineering'],
        'information_technology' => ['ar' => 'تقنية المعلومات', 'en' => 'Information Technology'],
        'information_systems' => ['ar' => 'نظم المعلومات', 'en' => 'Information Systems'],
        'cybersecurity' => ['ar' => 'الأمن السيبراني', 'en' => 'Cybersecurity'],
        'data_science' => ['ar' => 'علوم البيانات', 'en' => 'Data Science'],
        'artificial_intelligence' => ['ar' => 'الذكاء الاصطناعي', 'en' => 'Artificial Intelligence'],
        'computer_engineering' => ['ar' => 'هندسة الحاسب', 'en' => 'Computer Engineering'],
        'networks' => ['ar' => 'هندسة الشبكات', 'en' => 'Network Engineering'],
        'cloud_computing' => ['ar' => 'الحوسبة السحابية', 'en' => 'Cloud Computing'],
        'health_informatics' => ['ar' => 'المعلوماتية الصحية', 'en' => 'Health Informatics'],
        'programming' => ['ar' => 'البرمجة وتطوير التطبيقات', 'en' => 'Programming and Application Development'],
        'web_development' => ['ar' => 'تطوير الويب', 'en' => 'Web Development'],
        'mobile_development' => ['ar' => 'تطوير تطبيقات الجوال', 'en' => 'Mobile Application Development'],
        'database_management' => ['ar' => 'إدارة قواعد البيانات', 'en' => 'Database Management'],
        'data_analytics' => ['ar' => 'تحليل البيانات', 'en' => 'Data Analytics'],
        'network_security' => ['ar' => 'أمن الشبكات', 'en' => 'Network Security'],
        'cloud_architecture' => ['ar' => 'هندسة الحوسبة السحابية', 'en' => 'Cloud Architecture'],
        'devops' => ['ar' => 'هندسة التطوير والتشغيل', 'en' => 'DevOps Engineering'],
        'robotics' => ['ar' => 'الروبوتات والأنظمة الذكية', 'en' => 'Robotics and Intelligent Systems'],
        'game_development' => ['ar' => 'تطوير الألعاب', 'en' => 'Game Development'],
        'bioinformatics' => ['ar' => 'المعلوماتية الحيوية', 'en' => 'Bioinformatics'],
        'computer_graphics' => ['ar' => 'الرسوميات الحاسوبية', 'en' => 'Computer Graphics'],
    ],
];
